Add/docstrings
tue-robotics/geolib2 pull request #47
Opened 2022-01-04 19:24 UTC by PetervDooren

2022-01-04 19:40 UTC, MatthijsBurgh commented on include/geolib/CompositeShape.h
> +     * pairs of child shapes and the transform from the origin of the child shape
```suggestion
     * Pairs of child shapes and the transform from the origin of the child shape
```

2022-01-04 19:42 UTC, MatthijsBurgh requested changes
Please be consistent with Capital letters at the start of lines.

Also please generate the documentation locally to check if everything ends up correctly.

2022-01-08 11:37 UTC, PetervDooren commented
tested locally. documentation is confirmed to be better than it was.

2022-01-08 14:28 UTC, MatthijsBurgh approved these changes

2022-01-08 14:28 UTC, merged